services:
  afbb-mongo:
    image: mongo:8
    container_name: afbb-mongo
    ports:
      - 27017:27017
    volumes:
      - ./afbb-db/mongo:/docker-entrypoint-initdb.d
  afbb-webflux:
    image: gradle:8-jdk21
    container_name: afbb-webflux
    ports:
      - 8080:8080
    volumes:
      - ./afbb-webflux:/workspace:delegated
    command: tail -f /dev/null
  afbb-shop:
    image: node:23-bookworm-slim
    container_name: afbb-shop
    ports:
      - 5147:5147
    volumes:
      - ./afbb-shop:/workspace:delegated
    command: tail -f /dev/null