GET http://localhost:8080/categories HTTP/1.1
Content-Type: application/json

###

GET http://localhost:8080/categories?id=68818968edf9b41dfcdeed82 HTTP/1.1
Content-Type: application/json

###

POST http://localhost:8080/categories HTTP/1.1
Content-Type: application/json

[
  {
    "id": "6882fac9e10056069a9a619a",
    "description": "Dairy encompasses foods derived from or containing milk produced by mammals like cows, goats, and sheep.",
    "imageSrc": "https://picsum.photos/300/200",
    "name": "dairy"
  },
  {
    "id": "6882fac9e10056069a9a619b",
    "description": "Meat, in its primary definition, refers to the edible tissues of animals consumed as food.",
    "imageSrc": "https://picsum.photos/300/200",
    "name": "meat"
  },
  {
    "id": "6882fac9e10056069a9a619c",
    "description": "A bakery is a place where baked goods, primarily those made with flour, are produced and sold. These goods are typically prepared using an oven.",
    "imageSrc": "https://picsum.photos/300/200",
    "name": "bakery"
  },
  {
    "id": "6882fac9e10056069a9a619d",
    "description": "Vegetables are an essential part of a healthy and balanced diet due to their high nutritional value.",
    "imageSrc": "https://picsum.photos/300/200",
    "name": "vegetables"
  }
]

###

DELETE http://localhost:8080/categories HTTP/1.1
Content-Type: application/json

###

DELETE http://localhost:8080/categories?id=6882edfa894fd37173b8d7eb HTTP/1.1
Content-Type: application/json