GET http://localhost:8080/items HTTP/1.1
Content-Type: application/json

###

GET http://localhost:8080/items?id=6881958f709fd0194b367f10 HTTP/1.1
Content-Type: application/json

###

GET http://localhost:8080/items/category?categoryId=68818968edf9b41dfcdeed85 HTTP/1.1
Content-Type: application/json

###

POST http://localhost:8080/items HTTP/1.1
Content-Type: application/json

[
  {
    "id": "6881958f709fd0194b367f10",
    "categoryId": "68818968edf9b41dfcdeed82",
    "description": "Semi skimmed milk (1L)",
    "imageSrc": "https://picsum.photos/300/200",
    "name": "milk",
    "price": 1.7
  },
  {
    "id": "6881958f709fd0194b367f11",
    "categoryId": "68818968edf9b41dfcdeed82",
    "description": "Mild cheddar cheese (330g)",
    "imageSrc": "https://picsum.photos/300/200",
    "name": "cheese",
    "price": 2.39
  },
  {
    "id": "6881958f709fd0194b367f12",
    "categoryId": "68818968edf9b41dfcdeed82",
    "description": "Unsalted butter (250g)",
    "imageSrc": "https://picsum.photos/300/200",
    "name": "butter",
    "price": 1.09
  },
  {
    "id": "6881958f709fd0194b367f13",
    "categoryId": "68818968edf9b41dfcdeed82",
    "description": "Medium sized package (6 eggs)",
    "imageSrc": "https://picsum.photos/300/200",
    "name": "eggs",
    "price": 1.76
  },
  {
    "id": "6881958f709fd0194b367f14",
    "categoryId": "68818968edf9b41dfcdeed83",
    "description": "Rolled in fresh herbs<br>2 patties (250g)",
    "imageSrc": "https://picsum.photos/300/200",
    "name": "patties",
    "price": 2.29
  },
  {
    "id": "6881958f709fd0194b367f15",
    "categoryId": "68818968edf9b41dfcdeed83",
    "description": "Matured and organic ham (70g)",
    "imageSrc": "https://picsum.photos/300/200",
    "name": "ham",
    "price": 3.49
  },
  {
    "id": "6881958f709fd0194b367f16",
    "categoryId": "68818968edf9b41dfcdeed83",
    "description": "Free range chicken whole meat (250g)",
    "imageSrc": "https://picsum.photos/300/200",
    "name": "chicken",
    "price": 5.59
  },
  {
    "id": "6881958f709fd0194b367f17",
    "categoryId": "68818968edf9b41dfcdeed83",
    "description": "Reduced fat, pork, pack of three sausages (350g)",
    "imageSrc": "https://picsum.photos/300/200",
    "name": "sausages",
    "price": 4.55
  },
  {
    "id": "6881958f709fd0194b367f18",
    "categoryId": "68818968edf9b41dfcdeed84",
    "description": "Plain white bread (250g)",
    "imageSrc": "https://picsum.photos/300/200",
    "name": "loaf",
    "price": 1.89
  },
  {
    "id": "6881958f709fd0194b367f19",
    "categoryId": "68818968edf9b41dfcdeed84",
    "description": "Whole grain bread (70g)",
    "imageSrc": "https://picsum.photos/300/200",
    "name": "bagel",
    "price": 7.5
  },
  {
    "id": "6881958f709fd0194b367f1a",
    "categoryId": "68818968edf9b41dfcdeed84",
    "description": "Over baked bread (250g)",
    "imageSrc": "https://picsum.photos/300/200",
    "name": "bun",
    "price": 8.0
  },
  {
    "id": "6881958f709fd0194b367f1b",
    "categoryId": "68818968edf9b41dfcdeed84",
    "description": "Mint chocolate cookies (12)",
    "imageSrc": "https://picsum.photos/300/200",
    "name": "cookies",
    "price": 10.11
  },
  {
    "id": "6881958f709fd0194b367f1c",
    "categoryId": "68818968edf9b41dfcdeed85",
    "description": "Seedless juicy watermelon (250g)",
    "imageSrc": "https://picsum.photos/300/200",
    "name": "watermelon",
    "price": 1.2
  },
  {
    "id": "6881958f709fd0194b367f1d",
    "categoryId": "68818968edf9b41dfcdeed85",
    "description": "Multi purposes black currants (70g)",
    "imageSrc": "https://picsum.photos/300/200",
    "name": "currants",
    "price": 7.22
  },
  {
    "id": "6881958f709fd0194b367f1e",
    "categoryId": "68818968edf9b41dfcdeed85",
    "description": "Organic green broccoli (250g)",
    "imageSrc": "https://picsum.photos/300/200",
    "name": "broccoli",
    "price": 3.01
  },
  {
    "id": "6881958f709fd0194b367f1f",
    "categoryId": "68818968edf9b41dfcdeed85",
    "description": "Mixed white and yellow whole kernel corns (12)",
    "imageSrc": "https://picsum.photos/300/200",
    "name": "corn",
    "price": 6.77
  }
]

###

DELETE http://localhost:8080/items HTTP/1.1
Content-Type: application/json

###

DELETE http://localhost:8080/items?id=687f0861454805d13ff6badb HTTP/1.1
Content-Type: application/json