micronaut:
  application:
    name: afbb-ws
  server:
    cors:
      enabled: true
      origins: ${CORS_ALLOWED_ORIGINS}
      methods: GET,POST,PUT,DELETE,OPTIONS
  security:
    enabled: true
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_SECRET:pleaseChangeThisSecretForANewOne}"'
        generator:
          access-token:
            expiration: 3600
          refresh-token:
            secret: '"${JWT_REFRESH_SECRET:pleaseChangeThisSecretForANewOne}"'
mongodb:
  uri: ${DB_URI}