services:
  afbb-db:
    image: mongo:latest
    container_name: afbb-db
    user: "0:0"
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: afbb
    volumes:
      - ./mongo:/docker-entrypoint-initdb.d
